name: Docker-based Test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run docker-compose test
      run: |
        docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
